definitions:
  errorCommon.ResError:
    properties:
      errType:
        type: string
      msg:
        type: string
    type: object
  request.ReqDeleteProduct:
    properties:
      productID:
        type: string
    required:
    - productID
    type: object
  request.ReqUpdateProduct:
    properties:
      category:
        description: 상품 카테고리
        type: string
      description:
        description: 상품 설명
        type: string
      endDate:
        description: 예매 종료 날짜 epoch time
        type: integer
      name:
        description: 상품이름
        type: string
      perAmount:
        description: 상품 티켓 당 금액
        type: integer
      productID:
        type: string
      restCount:
        description: 남은 수량
        type: integer
      startDate:
        description: 예매 시작 날짜 epoch time
        type: integer
      totalCount:
        description: 총 수량
        type: integer
    required:
    - productID
    type: object
  request.ReqWithdrawalUser:
    properties:
      userID:
        type: string
    type: object
  response.GetsProduct:
    properties:
      category:
        description: 상품 카테고리
        type: string
      description:
        description: 상품 설명
        type: string
      endDate:
        description: 예매 종료 날짜 epoch time
        type: integer
      id:
        type: string
      image:
        description: 이미지
        type: string
      name:
        description: 상품이름
        type: string
      perAmount:
        description: 상품 티켓 당 금액
        type: integer
      restCount:
        description: 남은 수량
        type: integer
      startDate:
        description: 예매 시작 날짜 epoch time
        type: integer
      totalCount:
        description: 총 수량
        type: integer
    type: object
  response.ResGetProduct:
    properties:
      category:
        description: 상품 카테고리
        type: string
      description:
        description: 상품 설명
        type: string
      endDate:
        description: 예매 종료 날짜 epoch time
        type: integer
      id:
        type: string
      image:
        description: 이미지
        type: string
      name:
        description: 상품이름
        type: string
      perAmount:
        description: 상품 티켓 당 금액
        type: integer
      restCount:
        description: 남은 수량
        type: integer
      startDate:
        description: 예매 시작 날짜 epoch time
        type: integer
      totalCount:
        description: 총 수량
        type: integer
    type: object
  response.ResGetsProduct:
    properties:
      count:
        type: integer
      products:
        items:
          $ref: '#/definitions/response.GetsProduct'
        type: array
    type: object
info:
  contact: {}
paths:
  /v0.1/auth/google/signin:
    get:
      description: |-
        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorCommon.ResError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorCommon.ResError'
      summary: google 로그인
      tags:
      - auth
  /v0.1/auth/google/signin/callback:
    get:
      description: |-
        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorCommon.ResError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorCommon.ResError'
      summary: google login callback
      tags:
      - auth
  /v0.1/auth/google/signout:
    get:
      description: |-
        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: accessToken
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorCommon.ResError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorCommon.ResError'
      summary: google 로그아웃
      tags:
      - auth
  /v0.1/auth/user/withdrawal:
    post:
      description: |-
        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqWithdrawalUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorCommon.ResError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorCommon.ResError'
      summary: 회원 탈퇴
      tags:
      - auth
  /v0.1/features/message/naver/sms:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류

        ■ errCode with 401
        TOKEN_BAD : 토큰 인증 실패
        POLICY_VIOLATION : 토큰 세션 정책 위반

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: phoneList
        in: formData
        items:
          type: string
        name: phoneList
        required: true
        type: array
      - description: contentType
        in: formData
        name: contentType
        required: true
        type: string
      - description: content
        in: formData
        name: content
        required: true
        type: string
      - description: smsType
        in: formData
        name: smsType
        required: true
        type: string
      - description: reserveTime
        in: formData
        name: reserveTime
        type: string
      - description: scheduleCode
        in: formData
        name: scheduleCode
        type: string
      - description: image
        in: formData
        name: image
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorCommon.ResError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorCommon.ResError'
      summary: 네이버 sms 메시지 전송
      tags:
      - message
  /v0.1/features/product:
    delete:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류

        ■ errCode with 401
        TOKEN_BAD : 토큰 인증 실패
        POLICY_VIOLATION : 토큰 세션 정책 위반

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqDeleteProduct'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorCommon.ResError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorCommon.ResError'
      summary: 상품 삭제하기(소프트)
      tags:
      - product
    get:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류

        ■ errCode with 401
        TOKEN_BAD : 토큰 인증 실패
        POLICY_VIOLATION : 토큰 세션 정책 위반

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: productID
        in: query
        name: productID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResGetProduct'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorCommon.ResError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorCommon.ResError'
      summary: 상품 상세정보 가져오기
      tags:
      - product
    post:
      description: |-
        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: description
        in: formData
        name: description
        required: true
        type: string
      - description: category
        in: formData
        name: category
        required: true
        type: string
      - description: image
        in: formData
        name: image
        type: file
      - description: perAmount
        in: formData
        name: perAmount
        required: true
        type: integer
      - description: totalCount
        in: formData
        name: totalCount
        required: true
        type: integer
      - description: restCount
        in: formData
        name: restCount
        required: true
        type: integer
      - description: startDate
        in: formData
        name: startDate
        required: true
        type: integer
      - description: endDate
        in: formData
        name: endDate
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorCommon.ResError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorCommon.ResError'
      summary: 상품 등록
      tags:
      - product
    put:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류

        ■ errCode with 401
        TOKEN_BAD : 토큰 인증 실패
        POLICY_VIOLATION : 토큰 세션 정책 위반

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqUpdateProduct'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorCommon.ResError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorCommon.ResError'
      summary: 상품 수정하기
      tags:
      - product
  /v0.1/features/product/gets:
    get:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류

        ■ errCode with 401
        TOKEN_BAD : 토큰 인증 실패
        POLICY_VIOLATION : 토큰 세션 정책 위반

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResGetsProduct'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorCommon.ResError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorCommon.ResError'
      summary: 상품 목록 가져오기
      tags:
      - product
swagger: "2.0"
