definitions:
  errorCommon.ResError:
    properties:
      errType:
        type: string
      msg:
        type: string
    type: object
  response.ResCallbackGoogleOAuth:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  response.ResSignInGoogleOAuth:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
info:
  contact: {}
paths:
  /v0.1/auth/google/signin:
    get:
      description: |-
        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResSignInGoogleOAuth'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorCommon.ResError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorCommon.ResError'
      summary: google 로그인
      tags:
      - auth
  /v0.1/auth/google/signin/callback:
    get:
      description: |-
        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResCallbackGoogleOAuth'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorCommon.ResError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorCommon.ResError'
      summary: google login callback
      tags:
      - auth
  /v0.1/auth/google/signout:
    get:
      description: |-
        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: accessToken
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorCommon.ResError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorCommon.ResError'
      summary: google 로그아웃
      tags:
      - auth
swagger: "2.0"
